In [1]:
import pandas as pd

In [2]:
county_csv_path = "Resources/us_county.csv"

In [3]:
county_df = pd.read_csv(county_csv_path)
county_df

,fips,county,state,state_code,male,female,median_age,population,female_percentage,lat,long
0,1001,Autauga County,Alabama,AL,26874,28326,37.8,55200,51.315217,32.534923,-86.642730
1,1003,Baldwin County,Alabama,AL,101188,106919,42.8,208107,51.376936,30.727479,-87.722564
2,1005,Barbour County,Alabama,AL,13697,12085,39.9,25782,46.873788,31.869581,-85.393210
3,1007,Bibb County,Alabama,AL,12152,10375,39.9,22527,46.055844,32.998628,-87.126475
4,1009,Blount County,Alabama,AL,28434,29211,40.8,57645,50.673953,33.980869,-86.567380
...,...,...,...,...,...,...,...,...,...,...,...
3215,72145,Vega Baja Municipio,Puerto Rico,NaN,25580,27791,40.7,53371,52.071350,18.428461,-66.397926
3216,72147,Vieques Municipio,Puerto Rico,NaN,4332,4439,43.6,8771,50.609965,18.122662,-65.439095
3217,72149,Villalba Municipio,Puerto Rico,NaN,11169,11824,38.8,22993,51.424347,18.128155,-66.472816
3218,72151,Yabucoa Municipio,Puerto Rico,NaN,16541,17608,42.5,34149,51.562271,18.070468,-65.896311
3219,72153,Yauco Municipio,Puerto Rico,NaN,17475,18964,43.0,36439,52.043141,18.079728,-66.858276

In [4]:
#Trying to find the missing rows
county_df.count()

fips                 3220
county               3220
state                3220
state_code           3141
male                 3220
female               3220
median_age           3220
population           3220
female_percentage    3220
lat                  3220
long                 3220
dtype: int64